Default options to empty string for jvm options
Fixes the following error if no jvm options are passed:

>>> scyjava.jvm.start_JVM()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: start_JVM() missing 1 required positional argument: 'options'