Set jgo's lenient mode when resolving components
Aside from generally being friendlier and more likely to succeed,
the specific motivation for this change is sc.fiji:fiji:2.17.0
on macos-arm64, which has a flaw in its POM hierarchy leading to:

  ValueError: No version available for dependency
  org.jogamp.gluegen:gluegen-rt:jar:natives-macosx-aarch64

(The proper classifier is natives-macosx-universal.)

Setting lenient mode avoids the flaw and lets Fiji work with scyjava.
Of course, the proper fix will be in pom-scijava-base + pom-scijava.