Stop installing and testing jep
* The jep tests do not pass reliably on macOS.

* Installing jep can trigger a build from source.

* The support for scyjava via jep is incomplete anyway, due to jep's
  lack of support for class reflection (i.e. the jclass function).

And now, on Windows CI with Python 3.13:

    LINK : fatal error LNK1104: cannot open file 'python313t.lib'
    error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX86\\x64\\link.exe' failed with exit code 1104
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for jep

  ERROR: Failed to build installable wheels for some pyproject.toml based projects (jep)
  Successfully built scyjava assertpy
  Failed to build jep

The jep mode is probably used by no one. We'll leave it in as-is, but
no more worrying about whether it still works, at least for now. :-(